# config.py
from dataclasses import dataclass, asdict
from pathlib import Path
from datetime import datetime

###
# MAJOR CONFIG UPDATE — 12-08-25
#
# Refactored the entire configuration system for stability, clarity,
# and safe checkpoint serialization.
#
# Key Changes:
# 1. Removed inheritance between config classes.
#    - MFCCConfig, MelSpecConfig, MLPConfig, CNNConfig, and AudioSlicerConfig
#      are now independent and represent distinct functional domains
#      (feature extraction, model training, audio slicing).
#
# 2. Split feature-extraction configs from training configs.
#    - MFCCConfig / MelSpecConfig now contain ONLY feature params.
#    - MLPConfig / CNNConfig now contain ONLY model/training hyperparameters.
#    - This removes hidden coupling and makes features reusable across models.
#
# 3. Checkpoints no longer store config dataclass objects.
#    - Instead, we save plain JSON-friendly dictionaries:
#         "config": { "mfcc": asdict(MFCC), "mlp": asdict(MLP), ... }
#    - This avoids brittle pickle behavior, improves compatibility with
#      .pyz/.exe packaging, and ensures old checkpoints remain loadable
#      after refactors.
#
# 4. Removed dynamic timestamp fields from static configs.
#    - Runtime metadata (like timestamps) is now generated by the slicer
#      or trainer when the operation occurs, not stored in the config.
#
# 5. Introduced global static config singletons.
#    - All config dataclasses are instantiated once in config.py
#      and imported where needed, ensuring consistency across the project.
#
# Summary:
#   The configuration system is now explicit, stable, serialization-safe,
#   and easier to extend for future architectures and experiments.
###


#
# RULE: Anytime you pass a “config container” loaded from a checkpoint → treat it as a dictionary.
#

# ---------------------------
# META
# ---------------------------
#PROJECT_MODE = "proto"
CONFIG_VERSION = "1.0.0"

# ---------------------------
# ROOT PATHS — STATIC CONSTANTS
# ---------------------------
# IMPORTANT:
# For packaged apps (pyz/exe), Path.cwd() is the correct root.
# For development, this still resolves correctly.
PROJECT_ROOT = Path.cwd().parent
DATASETS_ROOT = PROJECT_ROOT / "data" / "datasets"
#SOURCE_ROOT = PROJECT_ROOT / "source"
INFERENCE_ROOT = PROJECT_ROOT / "data" / "inference"
INFERENCE_CLIPS_ROOT = INFERENCE_ROOT / "sliced_clips"
INFERENCE_AUDIO_ROOT = INFERENCE_ROOT / "in_audio"
INFERENCE_OUTPUT_ROOT = INFERENCE_ROOT / "output"
CHECKPOINTS_ROOT = PROJECT_ROOT / "data" / "checkpoints"


# ---------------------------
# GLOBAL AUDIO CONSTANTS
# ---------------------------
TARGET_SR = 11025
CLIP_DURATION = 0.50


# ---------------------------
# CONFIG GROUPS (STATIC STRUCTS)
# ---------------------------
@dataclass(frozen=True)
class MFCCConfig:
    N_MFCC: int = 32
    BATCH_SIZE: int = 32
    #NORMALIZE_FEATURES: bool = False     # deprecated - replaced w/ scaler
    STANDARD_SCALER: bool = True
    NORMALIZE_AUDIO_VOLUME: bool = False #True
    ADD_PITCH_FEATURES: bool = True       # recent addition - make sure implemented correctly in ALL mfcc feature functions


@dataclass(frozen=True)
class MelSpecConfig:
    N_MELS: int = 64
    N_FFT: int = 512
    HOP_LENGTH: int = 256
    BATCH_SIZE: int = 32
    NORMALIZE_AUDIO_VOLUME: bool = False #True
    # TO_DB ? always true
    TO_DB: bool = True # ! not yet enforced ! (2/1)


@dataclass(frozen=True)
class MLPConfig:
    CHECKPOINTS_DIR: Path = CHECKPOINTS_ROOT / "mlp"
    DEFAULT_CKPT_NAME: str = f"mlp_v{CONFIG_VERSION}.ckpt"

    SAVE_CHECKPOINT: bool = True

    HIDDEN_DIM: int = 128
    NUM_HIDDEN_LAYERS: int = 2
    DROPOUT: float = 0.1

    LR: float = 1e-3
    DECAY: float = 1e-4

    EPOCHS: int = 10
    MAX_CLIP_NORM: float = 1.0
    ES_WINDOW_LEN: int = 4
    ES_SLOPE_LIMIT: float = -0.00015


@dataclass(frozen=True)
class CNNConfig:
    CHECKPOINTS_DIR: Path = CHECKPOINTS_ROOT / "cnn"
    DEFAULT_CKPT_NAME: str = f"cnn_v{CONFIG_VERSION}.ckpt"

    SAVE_CHECKPOINT: bool = True

    BASE_CHANNELS: int = 32
    NUM_BLOCKS: int = 3
    KERNEL_SIZE: int = 3
    HIDDEN_DIM: int = 256
    DROPOUT: float = 0.1

    LR: float = 1e-3
    DECAY: float = 1e-4

    EPOCHS: int = 3
    MAX_CLIP_NORM: float = 1.0
    ES_WINDOW_LEN: int = 4
    ES_SLOPE_LIMIT: float = -0.00015
    USE_AMP: bool = True


@dataclass(frozen=True)
class AudioSlicerConfig:
    MIN_IN_DB_THRESHOLD: float = -35
    MIN_SLICE_RMS_DB: float = -30

    HOP_LEN: int = 256 * 3
    MIN_SEP: float = 0.25

'''
@dataclass(frozen=True)
class NotePredictorConfig:
    CNN_WEIGHT: float = 0.75
    MLP_WEIGHT: float = 1 - CNN_WEIGHT
'''

'''
@dataclass(frozen=True)
class LiveMicConfig:
    GATE_DB: float = -37.5          # ignore below this
    ONSET_JUMP_DB: float = 6.0      # how sharp the rise must be
    MIN_SEP: float = 0.20           # seconds between onsets
    HANGOVER_OFF: float = 0.10      # seconds of quiet to end a note
    OFF_DB: float = -50.0           # consider "off" below this
'''

# ---------------------------
# STATIC INSTANCES (THE REAL CONFIG OBJECTS)
# ---------------------------
MFCC_CONFIG = MFCCConfig()
MELSPEC_CONFIG = MelSpecConfig()
MLP_CONFIG = MLPConfig()
CNN_CONFIG = CNNConfig()
SLICER_CONFIG = AudioSlicerConfig()







